route:
  path: "/wp-json/custom/v1/acf-sync/{id}"
  method: "PATCH"
allow:
  - identity_business_name
  - identity_website_url
  - identity_email
  - identity_phone
  - identity_logo_url
  - identity_owner_name
  - identity_role_title
  - identity_headshot_url
  - identity_suburb
  - identity_state
  - identity_abn
  - identity_insured
  - identity_business_type
  - identity_address
  - identity_address_uri
  - identity_website
  - identity_location_label
  - identity_services
  - identity_uri_phone
  - identity_uri_email
  - identity_uri_sms
  - identity_uri_whatsapp
  - social_links_facebook
  - social_links_instagram
  - social_links_linkedin
  - social_links_twitter
  - social_links_youtube
  - social_links_tiktok
  - social_links_pinterest
  - business_description
  - service_areas_csv
  - testimonial_quote
  - testimonial_reviewer
  - testimonial_location
  - testimonial_source_label
  - testimonial_source_url
  - testimonial_job_type
  - theme_primary_color
  - theme_accent_color
  - trust_qr_text
  - trust_google_rating
  - trust_google_review_count
  - trust_google_review_url
  - trust_review_button_link
  - trust_profile_video_url
  - trust_contact_form
  - trust_vcf_url
  - trust_award
  - trsut_award_link
  - service_2_title
  - service_2_subtitle
  - service_2_image_url
  - service_2_price_note
  - service_2_description
  - service_2_cta_label
  - service_2_cta_link
  - service_2_delivery_modes
  - service_2_inclusion_1
  - service_2_inclusion_2
  - service_2_inclusion_3
  - service_2_tags
  - service_2_video_url
  - service_2_price
  - service_3_title
  - service_3_subtitle
  - service_3_image_url
  - service_3_price_note
  - service_3_description
  - service_3_cta_label
  - service_3_cta_link
  - service_3_delivery_modes
  - service_3_inclusion_1
  - service_3_inclusion_2
  - service_3_Inclusion_3   # note the capital I to match ACF
  - service_3_tags
  - service_3_video_url
  - service_3_price
  # optionally include, if you choose to allow them:
  - account_company
  - account_subscription

