identity_owner_name:
  priority: required
  tools: [site_scraper]
  fallback: false
  constraints:
    min_length: 2
    no_generic_terms: true

identity_role_title:
  priority: required
  tools: [site_scraper]
  fallback: false
  constraints:
    min_length: 2
    no_generic_terms:
      - "Owner"
      - "Manager"
      - "Staff"

identity_headshot_url:
  priority: recommended
  tools: [site_scraper]
  fallback: false
  constraints:
    must_be_image: true
    allowed_extensions: [".jpg", ".jpeg", ".png", ".webp"]

identity_logo_url:
  priority: recommended
  tools: [site_scraper]
  fallback: true
  constraints:
    must_be_image: true
    allowed_extensions: [".jpg", ".jpeg", ".png", ".webp"]

identity_suburb:
  priority: optional
  tools: [site_scraper]
  fallback: false

identity_state:
  priority: required
  tools: [site_scraper]
  fallback: false

identity_abn:
  priority: recommended
  tools: [site_scraper]
  fallback: false

identity_insured:
  priority: optional
  tools: [site_scraper]
  fallback: false

identity_business_type:
  priority: required
  tools: [site_scraper]
  fallback: false

identity_address:
  priority: optional
  tools: [site_scraper]
  fallback: false

identity_address_uri:
  priority: derived
  tools: []
  fallback: false

identity_email:
  priority: required
  tools: [site_scraper]
  fallback: false
  constraints:
    format: email

identity_phone:
  priority: required
  tools: [site_scraper]
  fallback: false
  constraints:
    format: spaced_human_readable
    regex: "^\\+?[0-9 ]+$"

identity_website:
  priority: required
  tools: [site_scraper]
  fallback: false
  constraints:
    format: url

identity_location_label:
  priority: required
  tools: [site_scraper]
  fallback: false

identity_services:
  priority: optional
  tools: [site_scraper]
  fallback: false
  constraints:
    html_tag: div
    class: tag

identity_display_name:
  priority: derived
  tools: []
  fallback: false
  constraints:
    derived_from: [identity_owner_name, identity_business_name]

identity_verified:
  priority: derived
  tools: []
  fallback: false
  constraints:
    requires_valid: [identity_abn, identity_owner_name, identity_phone]

identity_uri_phone:
  priority: derived
  tools: []
  fallback: false

identity_uri_email:
  priority: derived
  tools: []
  fallback: false

identity_uri_sms:
  priority: derived
  tools: []
  fallback: false

identity_uri_whatsapp:
  priority: derived
  tools: []
  fallback: false

identity_business_name:
  priority: required
  tools: [site_scraper]
  fallback: false

identity_website_url:
  priority: derived
  tools: []
  fallback: false

# ===== Service Panels =====
# TODO: Add service panels mapping
# <full 02_service_panels.yaml from patch>
# Common constraints for inclusions
_inclusion_constraints: &_inclusion_constraints
  min_length: 2
  reject_values:
    - "TBC"
    - "Coming Soon"

# Common constraints for tags
_tag_constraints: &_tag_constraints
  allowed_values: ["featured service", "featured project", "featured product"]
  format: human_readable_single

# Common constraints for price note
_price_note_constraints: &_price_note_constraints
  max_length: 30
  allowed_phrases:
    - "plus GST"
    - "including GST"
    - "starting from"
    - "per month"

# Common constraints for price
_price_constraints: &_price_constraints
  max_length: 6
  regex: "^\\$?\\d+(?:\\.\\d{2})?$"

# ===== Service 1 =====
service_1_title:
  priority: required
  tools: [site_scraper]
  fallback: false

service_1_subtitle:
  priority: deprecated
  tools: [site_scraper]
  fallback: false

service_1_image_url:
  priority: recommended
  tools: [site_scraper]
  fallback: true
  constraints:
    must_be_image: true

service_1_price_note:
  priority: optional
  tools: [site_scraper]
  fallback: true
  constraints: *_price_note_constraints

service_1_description:
  priority: required
  tools: [site_scraper]
  fallback: false
  constraints:
    min_words: 30

service_1_cta_label:
  priority: required
  tools: [site_scraper]
  fallback: true
  fallback_value: "Get a Quote"

service_1_cta_link:
  priority: required
  tools: [site_scraper]
  fallback: true

service_1_delivery_modes:
  priority: optional
  tools: [site_scraper]
  fallback: true
  format: ["Onsite", "Remote", "Melbourne", "Australia-wide"]

service_1_inclusion_1:
  priority: required
  tools: [site_scraper]
  fallback: true
  constraints: *_inclusion_constraints

service_1_tags:
  priority: required
  tools: [site_scraper]
  fallback: true
  constraints: *_tag_constraints

service_1_video_url:
  priority: optional
  tools: [site_scraper]
  fallback: false

service_1_price:
  priority: optional
  tools: [site_scraper]
  fallback: false
  constraints: *_price_constraints

service_1_inclusion_2:
  priority: required
  tools: [site_scraper]
  fallback: true
  constraints: *_inclusion_constraints

service_1_inclusion_3:
  priority: required
  tools: [site_scraper]
  fallback: true
  constraints: *_inclusion_constraints

service_1_panel_tag:
  priority: required
  tools: [site_scraper]
  fallback: false
  constraints:
    allowed_values: ["featured service", "featured project", "featured product"]

# ===== Service 2 =====
service_2_title:
  priority: required
  tools: [site_scraper]
  fallback: false

service_2_subtitle:
  priority: deprecated
  tools: [site_scraper]
  fallback: false

service_2_image_url:
  priority: recommended
  tools: [site_scraper]
  fallback: true
  constraints:
    must_be_image: true

service_2_price_note:
  priority: optional
  tools: [site_scraper]
  fallback: true
  constraints: *_price_note_constraints

service_2_description:
  priority: required
  tools: [site_scraper]
  fallback: false
  constraints:
    min_words: 30

service_2_cta_label:
  priority: required
  tools: [site_scraper]
  fallback: true
  fallback_value: "Get a Quote"

service_2_cta_link:
  priority: required
  tools: [site_scraper]
  fallback: true

service_2_delivery_modes:
  priority: optional
  tools: [site_scraper]
  fallback: true
  format: ["Onsite", "Remote", "Melbourne", "Australia-wide"]

service_2_inclusion_1:
  priority: required
  tools: [site_scraper]
  fallback: true
  constraints: *_inclusion_constraints

service_2_tags:
  priority: required
  tools: [site_scraper]
  fallback: true
  constraints: *_tag_constraints

service_2_video_url:
  priority: optional
  tools: [site_scraper]
  fallback: false

service_2_price:
  priority: optional
  tools: [site_scraper]
  fallback: false
  constraints: *_price_constraints

service_2_inclusion_2:
  priority: required
  tools: [site_scraper]
  fallback: true
  constraints: *_inclusion_constraints

service_2_inclusion_3:
  priority: required
  tools: [site_scraper]
  fallback: true
  constraints: *_inclusion_constraints

service_2_panel_tag:
  priority: required
  tools: [site_scraper]
  fallback: false
  constraints:
    allowed_values: ["featured service", "featured project", "featured product"]

# ===== Service 3 =====
service_3_title:
  priority: required
  tools: [site_scraper]
  fallback: false

service_3_subtitle:
  priority: deprecated
  tools: [site_scraper]
  fallback: false

service_3_image_url:
  priority: recommended
  tools: [site_scraper]
  fallback: true
  constraints:
    must_be_image: true

service_3_price_note:
  priority: optional
  tools: [site_scraper]
  fallback: true
  constraints: *_price_note_constraints

service_3_description:
  priority: required
  tools: [site_scraper]
  fallback: false
  constraints:
    min_words: 30

service_3_cta_label:
  priority: required
  tools: [site_scraper]
  fallback: true
  fallback_value: "Get a Quote"

service_3_cta_link:
  priority: required
  tools: [site_scraper]
  fallback: true

service_3_delivery_modes:
  priority: optional
  tools: [site_scraper]
  fallback: true
  format: ["Onsite", "Remote", "Melbourne", "Australia-wide"]

service_3_inclusion_1:
  priority: required
  tools: [site_scraper]
  fallback: true
  constraints: *_inclusion_constraints

service_3_tags:
  priority: required
  tools: [site_scraper]
  fallback: true
  constraints: *_tag_constraints

service_3_video_url:
  priority: optional
  tools: [site_scraper]
  fallback: false

service_3_price:
  priority: optional
  tools: [site_scraper]
  fallback: false
  constraints: *_price_constraints

service_3_inclusion_2:
  priority: required
  tools: [site_scraper]
  fallback: true
  constraints: *_inclusion_constraints

service_3_Inclusion_3:
  priority: required
  tools: [site_scraper]
  fallback: true
  constraints: *_inclusion_constraints

service_3_panel_tag:
  priority: required
  tools: [site_scraper]
  fallback: false
  constraints:
    allowed_values: ["featured service", "featured project", "featured product"]

account_company:
  priority: optional
  tools: []
  fallback: false
  constraints:
    min_length: 2

account_subscription:
  priority: optional
  tools: []
  fallback: false
  constraints:
    min_length: 2
# ===== Trust & Visual =====
# TODO: Add trust & visual mapping
# <full 03_trust_visual.yaml from patch>
trust_qr_text:
  priority: required
  tools: []
  fallback: false
  constraints:
    derived_from: tradecard_url

trust_google_rating:
  priority: required_if_trust_google_review_url
  tools: [gmb_lookup]
  fallback: false
  constraints:
    format: decimal
    decimal_places: 1
    min: 0
    max: 5

trust_google_review_count:
  priority: required_if_trust_google_review_url
  tools: [gmb_lookup]
  fallback: false
  constraints:
    format: integer
    min: 1

trust_google_review_url:
  priority: required
  tools: [gmb_lookup]
  fallback: false
  constraints:
    format: url

trust_review_button_link:
  priority: derived
  tools: []
  fallback: false
  constraints:
    format: url
    derived_from: trust_google_review_url

trust_profile_video_url:
  priority: optional
  tools: [site_scraper]
  fallback: true
  fallback_source: profile_video_url
  constraints:
    format: url
    must_be_video: true
    allowed_domains:
      - "youtube.com"
      - "youtu.be"
      - "vimeo.com"

trust_award:
  priority: optional
  tools: [site_scraper]
  fallback: false
  constraints:
    min_length: 2

trust_award_link:
  priority: recommended_if_trust_award
  tools: [site_scraper]
  fallback: false
  constraints:
    format: url

theme_accent_color:
  priority: required
  tools: []
  fallback: false
  constraints:
    format: hex_color
    must_start_with: "#"
    derived_from: theme_primary_color
    derivation: darken_by_10_percent

trust_contact_form:
  priority: optional
  tools: [site_scraper]
  fallback: false

theme_primary_color:
  priority: required
  tools: [site_scraper]
  fallback: true
  fallback_value: "#000000"
  constraints:
    format: hex_color
    must_start_with: "#"

trust_vcf_url:
  priority: derived
  tools: []
  fallback: false
  constraints:
    format: url
    derived_from: tradecard_url
# ===== Social Links =====
# TODO: Add social links mapping
# <full 04_social_links.yaml from patch>
social_links_facebook:
  priority: recommended
  tools: [site_scraper]
  fallback: true
  fallback_source: gmb_lookup
  constraints:
    format: url
    must_start_with: "https://"
    reject_placeholders: ["#", "/", ""]
    strip_query_params: ["utm_", "fbclid"]
    lowercase_except_protocol: true
    must_contain: "facebook.com"

social_links_instagram:
  priority: recommended
  tools: [site_scraper]
  fallback: true
  fallback_source: gmb_lookup
  constraints:
    format: url
    must_start_with: "https://"
    reject_placeholders: ["#", "/", ""]
    strip_query_params: ["utm_", "fbclid"]
    lowercase_except_protocol: true
    must_contain: "instagram.com"

social_links_linkedin:
  priority: recommended
  tools: [site_scraper]
  fallback: true
  fallback_source: gmb_lookup
  constraints:
    format: url
    must_start_with: "https://"
    reject_placeholders: ["#", "/", ""]
    strip_query_params: ["utm_", "fbclid"]
    lowercase_except_protocol: true
    must_contain: "linkedin.com"

social_links_pinterest:
  priority: recommended
  tools: [site_scraper]
  fallback: true
  fallback_source: gmb_lookup
  constraints:
    format: url
    must_start_with: "https://"
    reject_placeholders: ["#", "/", ""]
    strip_query_params: ["utm_", "fbclid"]
    lowercase_except_protocol: true
    must_contain: "pinterest.com"

social_links_tiktok:
  priority: recommended
  tools: [site_scraper]
  fallback: true
  fallback_source: gmb_lookup
  constraints:
    format: url
    must_start_with: "https://"
    reject_placeholders: ["#", "/", ""]
    strip_query_params: ["utm_", "fbclid"]
    lowercase_except_protocol: true
    must_contain: "tiktok.com"

social_links_twitter:
  priority: recommended
  tools: [site_scraper]
  fallback: true
  fallback_source: gmb_lookup
  constraints:
    format: url
    must_start_with: "https://"
    reject_placeholders: ["#", "/", ""]
    strip_query_params: ["utm_", "fbclid"]
    lowercase_except_protocol: true
    must_contain_any: ["x.com", "twitter.com"]
    prefer: "x.com"

social_links_youtube:
  priority: recommended
  tools: [site_scraper]
  fallback: true
  fallback_source: gmb_lookup
  constraints:
    format: url
    must_start_with: "https://"
    reject_placeholders: ["#", "/", ""]
    strip_query_params: ["utm_", "fbclid"]
    lowercase_except_protocol: true
    must_contain_any: ["youtube.com", "youtu.be"]

business_description:
  priority: recommended
  tools: [site_scraper]
  fallback: false
  constraints:
    min_words: 20
    max_length: 240

service_areas_csv:
  priority: optional
  tools: [site_scraper]
  fallback: false
  constraints:
    format: csv
# ===== Testimonials =====
# TODO: Add testimonials mapping
# <full 05_testimonials.yaml from patch>
testimonial_location:
  priority: required_if_testimonial
  tools: [site_scraper, gmb_lookup]
  fallback: nearest_capital_city
  constraints:
    min_length: 2
    must_be_valid_location: true

testimonial_quote:
  priority: required_if_testimonial
  tools: [site_scraper, gmb_lookup]
  fallback: false
  constraints:
    min_words: 20
    reviewer_required: true

testimonial_reviewer:
  priority: required_if_testimonial
  tools: [site_scraper, gmb_lookup]
  fallback: false
  constraints:
    min_length: 2
    no_generic_names:
      - "Verified Customer"
      - "Anonymous"
      - "Happy Client"

testimonial_source_label:
  priority: recommended_if_testimonial
  tools: [site_scraper, gmb_lookup]
  fallback: true
  constraints:
    min_length: 2
    derive_from_url_if_missing: true

testimonial_source_url:
  priority: recommended_if_testimonial
  tools: [site_scraper, gmb_lookup]
  fallback: false
  constraints:
    format: url

testimonial_job_type:
  priority: optional
  tools: [site_scraper]
  fallback: featured_service
policy:
  overall_min: 10
  required:
    - identity_business_name
    - identity_website_url
    - identity_services
  category_min:
    services: 1
    socials: 1
